# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='医生姓名')),
                ('level', models.IntegerField(choices=[(1, '主任医师'), (2, '副主任医师'), (3, '教授')], default=1, verbose_name='职称')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
            ],
        ),
        migrations.RemoveField(
            model_name='classlist',
            name='course',
        ),
        migrations.RemoveField(
            model_name='classlist',
            name='school',
        ),
        migrations.AlterField(
            model_name='department',
            name='intro',
            field=models.CharField(max_length=64, null=True, verbose_name='科室简介'),
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=16, verbose_name='科室名称'),
        ),
        migrations.DeleteModel(
            name='ClassList',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.AddField(
            model_name='doctor',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Department', verbose_name='科室'),
        ),
    ]
