# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181126_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='患者姓名')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('disease', models.IntegerField(blank=True, choices=[(1, '痤疮'), (2, '湿疹'), (3, '白癜风'), (4, '银屑病'), (5, '医学美容')], null=True, verbose_name='病种')),
                ('count', models.IntegerField(default=0, verbose_name='就诊次数')),
                ('intro', models.CharField(blank=True, max_length=64, null=True, verbose_name='病情描述')),
            ],
        ),
    ]
